name: 'Emergency Theme Backup'
description: 'Automatically creates and maintains an Emergency Theme backup branch on every merge or push to main, no tokens required.'
author: 'Michael Rojas'
branding:
  icon: 'refresh-ccw'
  color: 'blue'

runs:
  using: 'node20'
  main: 'index.js'

inputs:
  branch_name:
    description: 'Name of the backup branch (default: Emergency-Theme)'
    required: false
    default: 'Emergency-Theme'
